# Generated by Django 5.1.7 on 2025-03-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('mood_choice', models.CharField(choices=[('very_happy', '😊 Bardzo szczęśliwy'), ('happy', '🙂 Szczęśliwy'), ('neutral', '😐 Neutralny'), ('sad', '☹️ Smutny'), ('very_sad', '😢 Bardzo smutny'), ('stressed', '😖 Zestresowany'), ('anxious', '😟 Zaniepokojony'), ('tired', '😴 Zmęczony'), ('angry', '😡 Zły')], default='neutral', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('in_progress', 'W trakcie'), ('completed', 'Zakończone')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
