# Generated by Django 5.1.7 on 2025-04-13 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_conversation_options_remove_conversation_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='session_key',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
