# Generated by Django 5.1.7 on 2025-04-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_conversation_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
