# Generated by Django 5.1.7 on 2025-04-27 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_task_done_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('type', models.CharField(choices=[('expense', 'Wydatek'), ('income', 'Przychód')], max_length=10, verbose_name='Typ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kategoria finansowa',
                'verbose_name_plural': 'Kategorie finansowe',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Opis')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data transakcji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('expense', 'Wydatek'), ('income', 'Przychód')], max_length=10, verbose_name='Typ transakcji')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='myapp.category', verbose_name='Kategoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transakcja',
                'verbose_name_plural': 'Transakcje',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
