# Generated by Django 5.1.7 on 2025-04-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_category_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at'], 'verbose_name': 'Zadanie', 'verbose_name_plural': 'Zadania w dzienniku'},
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('expense', 'Wydatek'), ('income', 'Przychód'), ('saving', 'Oszczędność')], max_length=10, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('expense', 'Wydatek'), ('income', 'Przychód'), ('saving', 'Oszczędność')], max_length=10, verbose_name='Typ transakcji'),
        ),
    ]
